"""Dependency-free database constraint definitions shared by models and migrations."""

from typing import Final

REFERRAL_REWARDS_DURABLE_STATE_CONSTRAINT_NAME: Final[str] = "ck_referral_rewards_durable_state"
REFERRAL_REWARD_RESOLUTIONS_DECISION_CONSTRAINT_NAME: Final[str] = (
    "ck_referral_reward_resolutions_decision"
)
REFERRAL_REWARD_RESOLUTIONS_DECISION_CONSTRAINT_V2_SQL: Final[str] = (
    "decision IN ('CONFIRM_ISSUED', 'CANCEL', 'RETRY_PROVEN_MISSING', "
    "'CONFIRM_ADMIN_COMPENSATED', 'RETRY_OPERATOR_DIRECTED', "
    "'ACK_ADMIN_COMPENSATED_REFUND') AND "
    "((decision IN ('RETRY_PROVEN_MISSING', 'CONFIRM_ADMIN_COMPENSATED') "
    "AND selected_provenance IS NOT NULL "
    "AND jsonb_typeof(selected_provenance) = 'object' "
    "AND evidence_sha256 IS NOT NULL "
    "AND evidence_sha256 ~ '^[0-9a-f]{64}$' "
    "AND selected_source_transaction_id IS NOT NULL "
    "AND selected_origin_referral_id IS NOT NULL "
    "AND selected_level IS NOT NULL "
    "AND authorization_manifest_sha256 IS NOT NULL "
    "AND authorization_manifest_sha256 ~ '^[0-9a-f]{64}$') OR "
    "(decision = 'RETRY_OPERATOR_DIRECTED' "
    "AND selected_provenance IS NOT NULL "
    "AND jsonb_typeof(selected_provenance) = 'object' "
    "AND evidence_sha256 IS NOT NULL "
    "AND evidence_sha256 ~ '^[0-9a-f]{64}$' "
    "AND selected_source_transaction_id IS NOT NULL "
    "AND selected_origin_referral_id IS NOT NULL "
    "AND selected_level IS NOT NULL "
    "AND source_status IS NOT NULL "
    "AND authorization_manifest_sha256 IS NOT NULL "
    "AND authorization_manifest_sha256 ~ '^[0-9a-f]{64}$') OR "
    "(decision = 'ACK_ADMIN_COMPENSATED_REFUND' "
    "AND selected_provenance IS NULL AND evidence_sha256 IS NULL "
    "AND selected_source_transaction_id IS NOT NULL "
    "AND selected_origin_referral_id IS NOT NULL "
    "AND selected_level IS NOT NULL "
    "AND authorization_manifest_sha256 IS NOT NULL "
    "AND authorization_manifest_sha256 ~ '^[0-9a-f]{64}$' "
    "AND source_status = 'REFUNDED' AND NOT allow_drift) OR "
    "(decision IN ('CONFIRM_ISSUED', 'CANCEL') "
    "AND selected_provenance IS NULL AND evidence_sha256 IS NULL "
    "AND selected_source_transaction_id IS NULL "
    "AND selected_origin_referral_id IS NULL "
    "AND selected_level IS NULL "
    "AND authorization_manifest_sha256 IS NULL))"
)
REFERRAL_REWARDS_DURABLE_STATE_CONSTRAINT_V2_SQL: Final[str] = (
    "((state = 'ISSUED' AND is_issued AND issued_at IS NOT NULL "
    "AND processing_token_hash IS NULL AND processing_lease_expires_at IS NULL) OR "
    "(state = 'PROCESSING' AND NOT is_issued "
    "AND processing_token_hash IS NOT NULL "
    "AND processing_lease_expires_at IS NOT NULL) OR "
    "(state IN ('PENDING', 'RETRY_WAITING', 'SUPERSEDED') "
    "AND NOT is_issued AND processing_token_hash IS NULL "
    "AND processing_lease_expires_at IS NULL) OR "
    "(state = 'MANUAL_REQUIRED' AND processing_token_hash IS NULL "
    "AND processing_lease_expires_at IS NULL "
    "AND ((NOT is_issued) OR (is_issued AND issued_at IS NOT NULL)))) AND "
    "((target_expire_at IS NULL AND baseline_expire_at IS NULL "
    "AND target_subscription_id IS NULL) OR "
    "(type = 'EXTRA_DAYS' AND target_expire_at IS NOT NULL "
    "AND baseline_expire_at IS NOT NULL AND target_subscription_id IS NOT NULL)) "
    "AND ((operator_recovery_manifest_sha256 IS NULL "
    "AND ((source_transaction_id IS NULL AND origin_referral_id IS NULL "
    "AND level IS NULL AND accrual_strategy_snapshot IS NULL "
    "AND accrual_strategy IS NULL AND reward_strategy IS NULL "
    "AND config_value IS NULL "
    "AND state IN ('ISSUED', 'MANUAL_REQUIRED', 'SUPERSEDED')) OR "
    "(source_transaction_id IS NOT NULL AND origin_referral_id IS NOT NULL "
    "AND level IS NOT NULL AND accrual_strategy_snapshot IS NOT NULL "
    "AND reward_strategy IS NOT NULL AND config_value IS NOT NULL "
    "AND ((accrual_strategy_snapshot = 'ON_FIRST_PAYMENT' "
    "AND (accrual_strategy IS NULL OR accrual_strategy = 'ON_FIRST_PAYMENT')) "
    "OR (accrual_strategy_snapshot = 'ON_EACH_PAYMENT' "
    "AND accrual_strategy = 'ON_EACH_PAYMENT'))))) OR "
    "(operator_recovery_manifest_sha256 IS NOT NULL "
    "AND operator_recovery_manifest_sha256 ~ '^[0-9a-f]{64}$' "
    "AND type = 'EXTRA_DAYS' "
    "AND source_transaction_id IS NULL AND origin_referral_id IS NULL "
    "AND level IS NULL AND accrual_strategy_snapshot IS NULL "
    "AND accrual_strategy IS NULL AND reward_strategy IS NULL "
    "AND config_value IS NULL))"
)

# Historical migrations import these names. Keep their exact pre-0055 SQL
# immutable so a fresh database can reach 0055 before the new reward column
# exists. Runtime metadata and migration 0055 use the explicit V2 constants.
REFERRAL_REWARD_RESOLUTIONS_DECISION_CONSTRAINT_SQL: Final[str] = (
    "decision IN ('CONFIRM_ISSUED', 'CANCEL', 'RETRY_PROVEN_MISSING', "
    "'CONFIRM_ADMIN_COMPENSATED', 'ACK_ADMIN_COMPENSATED_REFUND') AND "
    "((decision IN ('RETRY_PROVEN_MISSING', 'CONFIRM_ADMIN_COMPENSATED') "
    "AND selected_provenance IS NOT NULL "
    "AND jsonb_typeof(selected_provenance) = 'object' "
    "AND evidence_sha256 IS NOT NULL "
    "AND evidence_sha256 ~ '^[0-9a-f]{64}$' "
    "AND selected_source_transaction_id IS NOT NULL "
    "AND selected_origin_referral_id IS NOT NULL "
    "AND selected_level IS NOT NULL "
    "AND authorization_manifest_sha256 IS NOT NULL "
    "AND authorization_manifest_sha256 ~ '^[0-9a-f]{64}$') OR "
    "(decision = 'ACK_ADMIN_COMPENSATED_REFUND' "
    "AND selected_provenance IS NULL AND evidence_sha256 IS NULL "
    "AND selected_source_transaction_id IS NOT NULL "
    "AND selected_origin_referral_id IS NOT NULL "
    "AND selected_level IS NOT NULL "
    "AND authorization_manifest_sha256 IS NOT NULL "
    "AND authorization_manifest_sha256 ~ '^[0-9a-f]{64}$' "
    "AND source_status = 'REFUNDED' AND NOT allow_drift) OR "
    "(decision IN ('CONFIRM_ISSUED', 'CANCEL') "
    "AND selected_provenance IS NULL AND evidence_sha256 IS NULL "
    "AND selected_source_transaction_id IS NULL "
    "AND selected_origin_referral_id IS NULL "
    "AND selected_level IS NULL "
    "AND authorization_manifest_sha256 IS NULL))"
)
REFERRAL_REWARDS_DURABLE_STATE_CONSTRAINT_SQL: Final[str] = (
    "((state = 'ISSUED' AND is_issued AND issued_at IS NOT NULL "
    "AND processing_token_hash IS NULL AND processing_lease_expires_at IS NULL) OR "
    "(state = 'PROCESSING' AND NOT is_issued "
    "AND processing_token_hash IS NOT NULL "
    "AND processing_lease_expires_at IS NOT NULL) OR "
    "(state IN ('PENDING', 'RETRY_WAITING', 'SUPERSEDED') "
    "AND NOT is_issued AND processing_token_hash IS NULL "
    "AND processing_lease_expires_at IS NULL) OR "
    "(state = 'MANUAL_REQUIRED' AND processing_token_hash IS NULL "
    "AND processing_lease_expires_at IS NULL "
    "AND ((NOT is_issued) OR (is_issued AND issued_at IS NOT NULL)))) AND "
    "((target_expire_at IS NULL AND baseline_expire_at IS NULL "
    "AND target_subscription_id IS NULL) OR "
    "(type = 'EXTRA_DAYS' AND target_expire_at IS NOT NULL "
    "AND baseline_expire_at IS NOT NULL AND target_subscription_id IS NOT NULL)) "
    "AND ((source_transaction_id IS NULL AND origin_referral_id IS NULL "
    "AND level IS NULL AND accrual_strategy_snapshot IS NULL "
    "AND accrual_strategy IS NULL AND reward_strategy IS NULL "
    "AND config_value IS NULL "
    "AND state IN ('ISSUED', 'MANUAL_REQUIRED', 'SUPERSEDED')) OR "
    "(source_transaction_id IS NOT NULL AND origin_referral_id IS NOT NULL "
    "AND level IS NOT NULL AND accrual_strategy_snapshot IS NOT NULL "
    "AND reward_strategy IS NOT NULL AND config_value IS NOT NULL "
    "AND ((accrual_strategy_snapshot = 'ON_FIRST_PAYMENT' "
    "AND (accrual_strategy IS NULL OR accrual_strategy = 'ON_FIRST_PAYMENT')) "
    "OR (accrual_strategy_snapshot = 'ON_EACH_PAYMENT' "
    "AND accrual_strategy = 'ON_EACH_PAYMENT'))))"
)
